name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-only:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app
    
    - name: Build
      run: xcodebuild Macaw-Pro-iOS/Macaw Pro.xcodeproj 

#     - name: Run tests
#       run: swift test -v
